
<div class="bjui-pageHeader">
	
    <form  id="pagerForm" method="post" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
        <input type="hidden" name="__formguid__" value="default" />
        <input type="hidden" name="pageSize" value="<?php echo $this->pagesize; ?>">
        <input type="hidden" name="pageCurrent" value="<?php echo $this->pageid; ?>">
        <input type="hidden" name="orderField" value="${param.orderField}">
        <input type="hidden" name="orderDirection" value="${param.orderDirection}">
        <lable>支付流水号：</lable>
        <input type="text" name="out_trade_no" value="<?php echo $this->out_trade_no; ?>" />
        <lable>付款人id：</lable>
        <input type="text" name="payer_id" value="<?php echo $this->payer_id; ?>" />
        <button type="submit" class="btn-green">查询</button>
    </form>
	<div class="pull-right">
		
		<script>
			/*
			 构造表单 post 方法 提交
			 */
			var ids = new Array();
			$('.wares-export').click(function () {
				if (ids.length == 0) {
					$(document).alertmsg('error', '无选中选项');
					return false;
				}
				$('#wares-exportChecked').html('');
				for (var i in ids) {
					var reg = /function[.]*/;
					if (reg.exec(ids[i]) != null) {
						continue;
					}
					$('#wares-exportChecked').append("<input type='hidden' name='ids[]' value='" + ids[i] + "'>");
				}
				$('#wares-exportChecked').submit();
				//window.location.href="/index.php?__=manage/managers/index&__EXCEL__=1&ids="+ids;
				return false;
			});
		</script>
	</div>
</div>
<div class="bjui-pageContent tableContent">
	<table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true"
	       data-toggle="tablefixed">
		<thead>
		<tr><?php
			$header = $this->tableHeaders;
			foreach ($header as $k => $v) {
				echo "<th width = '" . $v . "'>";
				echo $k;
				echo "</th>";
			}
			?>
			<!--<th width="10"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
			<th width="40">操作</th>-->
		</tr>
		</thead>
		<tbody>
   
<?php
         if(!empty($this->records)) {
                    foreach($this->records as $r) {
                        echo "<tr><td>";
                        echo implode('</td><td>', $r);
                        echo "</td></tr>";
                    }
                }
		
		?>
		</tbody>
	</table>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close" data-icon="close">关闭</button></li>
    </ul>
    <div class="pages">
        <span>每页&nbsp;</span>
        <div class="selectPagesize">
            <select data-toggle="selectpicker" data-toggle-change="changepagesize">
                <?php
                $pager = $this->pager;
                
                $r = explode(',', $pager->enumPagesize);
                var_log($pager,'pager>>>>>>>>>>>>>>');
                foreach($r as $v){
                    $str .= "<option value=\"$v\">$v</option>";
                }
                echo $str;
                ?>
            </select>
        </div>
        <span>&nbsp;条，共 <?php echo $pager->total; ?> 条</span>
    </div>
       <div class="pagination-box" data-toggle="pagination" data-total="<?php echo $pager->total; ?>" data-page-size="<?php echo $pager->page_size; ?>" data-page-current="<?php echo $pager->pageid; ?>"></div>

</div>







