<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1),'index'); ?>" method="post" id="copartners-exportChecked" style="display: none;">
</form>
<label id="uriMark" style="display: none;"><?php echo \Sooh\Base\Tools::uri(null, 'getbatchids') ?></label>
<div class="bjui-pageHeader"><?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
    ?>
    <div class="pull-right">

        <?php
        // var_log(\Sooh\Base\Tools::uri(null,'edit'), 'editurl>>>>>');
        echo \Prj\Misc\View::btnAddInDatagrid(\Sooh\Base\Tools::uri(null,'create'));
        //echo '&nbsp';
        //echo \Prj\Misc\View::btnDelClickInDatagrid(\Sooh\Base\Tools::uri('ids={#bjui-selected}','xxx'));
        ?>

<!--        <div class="btn-group">-->
<!--            <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>-->
<!--            <ul class="dropdown-menu right" role="menu">-->
<!--                <li><a  href="--><?php //echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'index'); ?><!--">导出全部</a></li>-->
<!--                <li><a class="copartners-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>-->
<!--            </ul>-->
<!--        </div>-->
        <script>
            /*
             构造表单 post 方法 提交
             */
            var ids = new Array();
            $('.copartners-export').click(function(){
                if(ids.length==0)
                {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#copartners-exportChecked').html(''); //add ' '
                for(var i in ids)
                {
                    var reg = /function[.]*/;
                    if(reg.exec(ids[i])!=null)
                    {
                        continue;
                    }
                    $('#copartners-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                }
                $('#copartners-exportChecked').submit();
                //window.location.href="/index.php?__=manage/managers/index&__EXCEL__=1&ids="+ids;
                return false;
            });

//            $('#_grpId_eq').change(function() {
//                var uri = $('#uriMark').text();
//                var grpIdSelected = $('#_grpId_eq').val();
//                if(grpIdSelected) {
//                    uri = uri+"grpId="+grpIdSelected;
//                    $.get(uri, function(data, status){
//                        $("#_batchId_eq option").remove();
//                        for(i in data){
//                            var str = "<option value=\""+i+"\">"+data[i]+"</option>";
//                            $("#_batchId_eq").append(str);
//                        }
//                    });
//                }
//            });

        </script>
    </div>
</div>


<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>
        <tr><?php
			$header = $this->header;
			foreach ($header as $k => $v) {
				echo "<th width = '" . $v . "'>";
				echo $k;
				echo "</th>";
			}
			?>
			<th width="10"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
			<th width="40">操作</th>
		</tr>
        </thead>
        <tbody>
        <?php
        $records = $this->rs;
        if (!empty($records))
        {
            foreach ($records as $r){
                
                 $_pkey_ = $r['_pkey_val_'];
				echo "<tr data-id=\"{$_pkey_}\">";
				unset($r['_pkey_val_']);
                foreach ($r as $k => $v) {
					echo "<td>";
					echo $v;
					echo "</td>";
				}
                
				echo '<td><input type="checkbox" name="ids" data-group="ids" data-toggle="icheck" value="' . $_pkey_ . '"></td>';
				echo '<td>';
				$flow = \Prj\Misc\View::btnAjax('删除',\Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_],'del'),'确定执行删除命令么?');
				echo $flow;
				echo \Prj\Misc\View::btnEditInDatagrid('修改',\Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_],'edit'));
                echo '</td>';
                echo "</tr>\n";
            }
        }
        ?>
        </tbody>
    </table>
</div>



<div class="bjui-pageFooter"><?php // echo \Prj\Misc\View::pagerStandard($this->pager);?></div>



