<table width="450">
    <tbody>
    <tr>
        <td height="101" width="274">
            <p>
                <strong>扫描右侧官方微信二维码，福利快人一步</strong>
            </p>
            <p>
                ·新产品第一时间知道，抢标我第一<br />
                ·优惠活动随时掌握，不会错过任何福利<br />
                ·更多线上互动，帮您了解小虾
            </p>
        </td>
        <td width="127">
            <img src="/index/public/getimage?fileId=manage_wares_14522475656654" alt="" align="right" height="98" width="100" /><br />
        </td>
    </tr>
    </tbody>
</table>
<table width="450">
    <tbody>
    <tr>
        <td>
            <p>
                <strong>产品介绍</strong>
            </p>
            <p>
                投资范围 <br />
                本基金主要投资于具有良好流动性的金融工具，包括国内依法发行上市的股票、债券、资产支持证券主要投资于经过中国证监会或中国银监会核准发行的金融衍生产品，包括但不限于基金、信托、银行理财、资产管理计划、有限合伙等。以及其他合法的货币市场工具如逆回购、协议存款等。
            </p>
            <p>
                投资目标 <br />
                在有效控制风险的前提下，通过把握行业周期轮换规律，动态调整基金股票资产在不同行业之间的配置比例，并且在此基础上通过进行积极
                的大类资产配置，力求实现基金资产净值长期稳定地持续增长。力争在保持一定流动性基础上，帮助投资者完成资产配置，中立客观的选择合适风险等级的产品。力争为投资者提供长期稳定的绝对收益回报，成为家庭资产配置的首选标的。
            </p>
        </td>
    </tr>
    </tbody>
</table>
<table width="450">
    <tbody>
    <tr>
        <td width="237">
            <strong>资产配置</strong>
        </td>
        <td width="170">
            <br />
        </td>
    </tr>
    <tr>
        <td>
            资产分布
        </td>
        <td>
            <br />
        </td>
    </tr>
    <tr>
        <td height="84">
            <img src="/index/public/getimage?fileId=manage_wares_14522475932089" alt="" height="94" width="100" /><br />
        </td>
        <td>
            <span style="color:#E56600;">■</span>股票<br />
            <span style="color:#FF9900;">■</span>债券<br />
            <span style="color:#FFE500;">■</span>其他投资
        </td>
    </tr>
    <tr>
        <td>
            行业配置
        </td>
        <td>
            <br />
        </td>
    </tr>
    <tr>
        <td height="99">
            <img src="/index/public/getimage?fileId=manage_wares_14522476026097" alt="" height="94" width="100" /><br />
        </td>
        <td>
            <span style="color:#003399;">■</span>制造业<br />
            <span style="color:#337FE5;">■</span>零售业<br />
            <span style="color:#00D5FF;">■</span>其他
        </td>
    </tr>
    </tbody>
</table>
<table width="450">
    <tbody>
    <tr>
        <td width="162">
            <strong>投顾介绍</strong>
        </td>
        <td width="245">
            <br />
        </td>
    </tr>
    <tr>
        <td>
            辛宇<br />
        </td>
        <td>
            <br />
        </td>
    </tr>
    <tr>
        <td height="72">
            <img src="/index/public/getimage?fileId=manage_wares_14522501619949" alt="" height="100" width="100" /><br />
        </td>
        <td>
            <p style="margin-left:0cm;text-indent:24.0pt;">
                武汉大学建筑学学士，经济学硕士，香港中文大学<span>FMBA</span>，深圳展博投资管理有限公司总经理，投资决策委员会主席。
            </p>
        </td>
    </tr>
    </tbody>
</table>
<table width="450">
    <tbody>
    <tr>
        <td align="center" valign="middle" width="135">
            <span>任期回报</span>
        </td>
        <td align="center" valign="middle" width="135">
            <span>任期最大盈利</span>
        </td>
        <td align="center" valign="middle" width="133">
            <span>任期最大回撤</span>
        </td>
    </tr>
    <tr>
        <td align="center" height="21" valign="middle">
            <span style="color:#E53333;"> +190.25%</span>
        </td>
        <td align="center" valign="middle">
            <span style="color:#E53333;"> +265.59%</span>
        </td>
        <td align="center" valign="middle">
            <span style="color:#009900;"> -5.65%</span>
        </td>
    </tr>
    </tbody>
</table>