<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `RouterF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Glacier2__t_Router;
global $Glacier2__t_RouterPrx;
if(!isset($Glacier2__t_Router))
{
    $Glacier2__t_Router = IcePHP_declareClass('::Glacier2::Router');
    $Glacier2__t_RouterPrx = IcePHP_declareProxy('::Glacier2::Router');
}
?>
