<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1, 'where'=>$this->where),'index'); ?>" method="post" id="contracts-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader"><?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
    ?>
    <div class="pull-right">

        <div class="btn-group">
            <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
            <ul class="dropdown-menu right" role="menu">
                <li><a  href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'index'); ?>">导出全部</a></li>
                <li><a class="contracts-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>
            </ul>
        </div>
        <script>
            /*
             构造表单 post 方法 提交
             */
            var ids = new Array();
            $('.contracts-export').click(function(){
                if(ids.length==0)
                {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#contracts-exportChecked').html(''); //add ' '
                for(var i in ids)
                {
                    var reg = /function[.]*/;
                    if(reg.exec(ids[i])!=null)
                    {
                        continue;
                    }
                    $('#contracts-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                }
                $('#contracts-exportChecked').submit();
                //window.location.href="/index.php?__=manage/managers/index&__EXCEL__=1&ids="+ids;
                return false;
            });
        </script>
    </div>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>
        <tr>
            <?php $headers=$this->headers;
            foreach($headers as $k=>$v){
                echo "<th width=\"$v\">$k</th>";
            }
            ?>
            <th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
            <th width="200">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php $records=$this->records;
        if (!empty($records)){
            foreach ($records as $r){
                $_pkey_ = $r['_pkey_'];
                echo "<tr data-id=\"{$_pkey_}\">";
                unset ($r['_pkey_']);
                echo '<td>'.implode('</td><td>', $r).'</td>';

                echo '<td>';
                echo '<input type="checkbox" name="ids" data-toggle="icheck" value="'.$_pkey_.'">';
                echo '</td>';
                echo '<td>';
//                echo \Prj\Misc\View::btnEditInDatagrid('upd',\Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_]));;
                echo \Prj\Misc\View::btnDefaultInDatagrid('日分布',\Sooh\Base\Tools::uri(['_pkey_'=>$_pkey_],'contractdaily'));
                echo \Prj\Misc\View::btnDefaultInDatagrid('用户分布',\Sooh\Base\Tools::uri(['_pkey_'=>$_pkey_],'user'));
                echo '</td>';
                echo '</tr>'."\n";
            }
        }
        ?>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>