// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `msgcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.msgcenter;

public interface bypush extends Ice.Object,
                                _bypushOperations, _bypushOperationsNC
{
    public static final String ice_staticId = "::sooh::services::msgcenter::bypush";

    public static final long serialVersionUID = -3033807433405237537L;
}
