// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `msgcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.msgcenter;

public interface _bysmsOperations
{
    /**
     * 发送验证码类短信，receiver是手机号
     * @param __current The Current object for the invocation.
     **/
    void sendCode(String receiver, String msg, Ice.Current __current);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __current The Current object for the invocation.
     **/
    void sendNotice(String receivers, String msg, Ice.Current __current);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __current The Current object for the invocation.
     **/
    void sendMarket(String receivers, String msg, Ice.Current __current);
}
