// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `msgcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.msgcenter;

/**
 * Provides type-specific helper functions.
 **/
public final class bypushPrxHelper extends Ice.ObjectPrxHelperBase implements bypushPrx
{
    private static final String __sendCmd_name = "sendCmd";

    public void sendCmd(String receivers, String cmd)
    {
        sendCmd(receivers, cmd, null, false);
    }

    public void sendCmd(String receivers, String cmd, java.util.Map<String, String> __ctx)
    {
        sendCmd(receivers, cmd, __ctx, true);
    }

    private void sendCmd(String receivers, String cmd, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_sendCmd(begin_sendCmd(receivers, cmd, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, String cmd)
    {
        return begin_sendCmd(receivers, cmd, null, false, false, null);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, String cmd, java.util.Map<String, String> __ctx)
    {
        return begin_sendCmd(receivers, cmd, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, String cmd, Ice.Callback __cb)
    {
        return begin_sendCmd(receivers, cmd, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, String cmd, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendCmd(receivers, cmd, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, String cmd, Callback_bypush_sendCmd __cb)
    {
        return begin_sendCmd(receivers, cmd, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, String cmd, java.util.Map<String, String> __ctx, Callback_bypush_sendCmd __cb)
    {
        return begin_sendCmd(receivers, cmd, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, 
                                         String cmd, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendCmd(receivers, cmd, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, 
                                         String cmd, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendCmd(receivers, cmd, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, 
                                         String cmd, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendCmd(receivers, cmd, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendCmd(String receivers, 
                                         String cmd, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendCmd(receivers, cmd, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sendCmd(String receivers, 
                                          String cmd, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendCmd(receivers, 
                             cmd, 
                             __ctx, 
                             __explicitCtx, 
                             __synchronous, 
                             new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_sendCmd(String receivers, 
                                          String cmd, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sendCmd_name, __cb);
        try
        {
            __result.prepare(__sendCmd_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(receivers);
            __os.writeString(cmd);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_sendCmd(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __sendCmd_name);
    }

    private static final String __sendMsg_name = "sendMsg";

    public void sendMsg(String receivers, String msg)
    {
        sendMsg(receivers, msg, null, false);
    }

    public void sendMsg(String receivers, String msg, java.util.Map<String, String> __ctx)
    {
        sendMsg(receivers, msg, __ctx, true);
    }

    private void sendMsg(String receivers, String msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_sendMsg(begin_sendMsg(receivers, msg, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, String msg)
    {
        return begin_sendMsg(receivers, msg, null, false, false, null);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, String msg, java.util.Map<String, String> __ctx)
    {
        return begin_sendMsg(receivers, msg, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, String msg, Ice.Callback __cb)
    {
        return begin_sendMsg(receivers, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendMsg(receivers, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, String msg, Callback_bypush_sendMsg __cb)
    {
        return begin_sendMsg(receivers, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, String msg, java.util.Map<String, String> __ctx, Callback_bypush_sendMsg __cb)
    {
        return begin_sendMsg(receivers, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, 
                                         String msg, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendMsg(receivers, msg, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, 
                                         String msg, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMsg(receivers, msg, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, 
                                         String msg, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendMsg(receivers, msg, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendMsg(String receivers, 
                                         String msg, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMsg(receivers, msg, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sendMsg(String receivers, 
                                          String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMsg(receivers, 
                             msg, 
                             __ctx, 
                             __explicitCtx, 
                             __synchronous, 
                             new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_sendMsg(String receivers, 
                                          String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sendMsg_name, __cb);
        try
        {
            __result.prepare(__sendMsg_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(receivers);
            __os.writeString(msg);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_sendMsg(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __sendMsg_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bypushPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), bypushPrx.class, bypushPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bypushPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), bypushPrx.class, bypushPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bypushPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), bypushPrx.class, bypushPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bypushPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), bypushPrx.class, bypushPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static bypushPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, bypushPrx.class, bypushPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static bypushPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, bypushPrx.class, bypushPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::sooh::services::msgcenter::bypush"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, bypushPrx v)
    {
        __os.writeProxy(v);
    }

    public static bypushPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            bypushPrxHelper result = new bypushPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
