// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `msgcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.msgcenter;

/**
 * Provides type-specific helper functions.
 **/
public final class bysmsPrxHelper extends Ice.ObjectPrxHelperBase implements bysmsPrx
{
    private static final String __sendCode_name = "sendCode";

    public void sendCode(String receiver, String msg)
    {
        sendCode(receiver, msg, null, false);
    }

    public void sendCode(String receiver, String msg, java.util.Map<String, String> __ctx)
    {
        sendCode(receiver, msg, __ctx, true);
    }

    private void sendCode(String receiver, String msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_sendCode(begin_sendCode(receiver, msg, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sendCode(String receiver, String msg)
    {
        return begin_sendCode(receiver, msg, null, false, false, null);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, String msg, java.util.Map<String, String> __ctx)
    {
        return begin_sendCode(receiver, msg, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, String msg, Ice.Callback __cb)
    {
        return begin_sendCode(receiver, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendCode(receiver, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, String msg, Callback_bysms_sendCode __cb)
    {
        return begin_sendCode(receiver, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, String msg, java.util.Map<String, String> __ctx, Callback_bysms_sendCode __cb)
    {
        return begin_sendCode(receiver, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendCode(receiver, msg, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendCode(receiver, msg, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendCode(receiver, msg, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendCode(receiver, msg, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sendCode(String receiver, 
                                           String msg, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendCode(receiver, 
                              msg, 
                              __ctx, 
                              __explicitCtx, 
                              __synchronous, 
                              new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_sendCode(String receiver, 
                                           String msg, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sendCode_name, __cb);
        try
        {
            __result.prepare(__sendCode_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(receiver);
            __os.writeString(msg);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_sendCode(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __sendCode_name);
    }

    private static final String __sendMarket_name = "sendMarket";

    public void sendMarket(String receivers, String msg)
    {
        sendMarket(receivers, msg, null, false);
    }

    public void sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx)
    {
        sendMarket(receivers, msg, __ctx, true);
    }

    private void sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_sendMarket(begin_sendMarket(receivers, msg, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, String msg)
    {
        return begin_sendMarket(receivers, msg, null, false, false, null);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx)
    {
        return begin_sendMarket(receivers, msg, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, Ice.Callback __cb)
    {
        return begin_sendMarket(receivers, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendMarket(receivers, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, Callback_bysms_sendMarket __cb)
    {
        return begin_sendMarket(receivers, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx, Callback_bysms_sendMarket __cb)
    {
        return begin_sendMarket(receivers, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendMarket(receivers, msg, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMarket(receivers, msg, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendMarket(receivers, msg, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMarket(receivers, msg, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sendMarket(String receivers, 
                                             String msg, 
                                             java.util.Map<String, String> __ctx, 
                                             boolean __explicitCtx, 
                                             boolean __synchronous, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMarket(receivers, 
                                msg, 
                                __ctx, 
                                __explicitCtx, 
                                __synchronous, 
                                new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_sendMarket(String receivers, 
                                             String msg, 
                                             java.util.Map<String, String> __ctx, 
                                             boolean __explicitCtx, 
                                             boolean __synchronous, 
                                             IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sendMarket_name, __cb);
        try
        {
            __result.prepare(__sendMarket_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(receivers);
            __os.writeString(msg);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_sendMarket(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __sendMarket_name);
    }

    private static final String __sendNotice_name = "sendNotice";

    public void sendNotice(String receivers, String msg)
    {
        sendNotice(receivers, msg, null, false);
    }

    public void sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx)
    {
        sendNotice(receivers, msg, __ctx, true);
    }

    private void sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_sendNotice(begin_sendNotice(receivers, msg, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, String msg)
    {
        return begin_sendNotice(receivers, msg, null, false, false, null);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx)
    {
        return begin_sendNotice(receivers, msg, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, Ice.Callback __cb)
    {
        return begin_sendNotice(receivers, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendNotice(receivers, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, Callback_bysms_sendNotice __cb)
    {
        return begin_sendNotice(receivers, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx, Callback_bysms_sendNotice __cb)
    {
        return begin_sendNotice(receivers, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendNotice(receivers, msg, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendNotice(receivers, msg, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendNotice(receivers, msg, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendNotice(receivers, msg, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sendNotice(String receivers, 
                                             String msg, 
                                             java.util.Map<String, String> __ctx, 
                                             boolean __explicitCtx, 
                                             boolean __synchronous, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendNotice(receivers, 
                                msg, 
                                __ctx, 
                                __explicitCtx, 
                                __synchronous, 
                                new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_sendNotice(String receivers, 
                                             String msg, 
                                             java.util.Map<String, String> __ctx, 
                                             boolean __explicitCtx, 
                                             boolean __synchronous, 
                                             IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sendNotice_name, __cb);
        try
        {
            __result.prepare(__sendNotice_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(receivers);
            __os.writeString(msg);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_sendNotice(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __sendNotice_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bysmsPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), bysmsPrx.class, bysmsPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bysmsPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), bysmsPrx.class, bysmsPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bysmsPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), bysmsPrx.class, bysmsPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static bysmsPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), bysmsPrx.class, bysmsPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static bysmsPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, bysmsPrx.class, bysmsPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static bysmsPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, bysmsPrx.class, bysmsPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::sooh::services::msgcenter::bysms"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, bysmsPrx v)
    {
        __os.writeProxy(v);
    }

    public static bysmsPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            bysmsPrxHelper result = new bysmsPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
