<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `PermissionsVerifier.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once __DIR__.'/../Glacier2/SSLInfo.php';

global $Glacier2__t_PermissionDeniedException;

if(!class_exists('Glacier2_PermissionDeniedException',false))
{
    class Glacier2_PermissionDeniedException extends Ice_UserException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'Glacier2::PermissionDeniedException';
        }

        public function __toString()
        {
            global $Glacier2__t_PermissionDeniedException;
            return IcePHP_stringifyException($this, $Glacier2__t_PermissionDeniedException);
        }

        public $reason;
    }

    $Glacier2__t_PermissionDeniedException = IcePHP_defineException('::Glacier2::PermissionDeniedException', 'Glacier2_PermissionDeniedException', true, null, array(
        array('reason', $IcePHP__t_string, false, 0)));
}

global $Glacier2__t_PermissionsVerifier;
global $Glacier2__t_PermissionsVerifierPrx;

if(!interface_exists('Glacier2_PermissionsVerifier',false))
{
    interface Glacier2_PermissionsVerifier extends Ice_Object
    {
        public function checkPermissions($userId, $password, $reason);
    }

    class Glacier2_PermissionsVerifierPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::Glacier2::PermissionsVerifier', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Glacier2::PermissionsVerifier', $facet);
        }

        public static function ice_staticId()
        {
            return '::Glacier2::PermissionsVerifier';
        }
    }

    $Glacier2__t_PermissionsVerifier = IcePHP_defineClass('::Glacier2::PermissionsVerifier', 'Glacier2_PermissionsVerifier', -1, true, false, $Ice__t_Object, null, null);

    $Glacier2__t_PermissionsVerifierPrx = IcePHP_defineProxy($Glacier2__t_PermissionsVerifier);

    IcePHP_defineOperation($Glacier2__t_PermissionsVerifier, 'checkPermissions', 2, 1, 2, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), array(array($IcePHP__t_string, false, 0)), array($IcePHP__t_bool, false, 0), array($Glacier2__t_PermissionDeniedException));
}

global $Glacier2__t_SSLPermissionsVerifier;
global $Glacier2__t_SSLPermissionsVerifierPrx;

if(!interface_exists('Glacier2_SSLPermissionsVerifier',false))
{
    interface Glacier2_SSLPermissionsVerifier extends Ice_Object
    {
        public function authorize($info, $reason);
    }

    class Glacier2_SSLPermissionsVerifierPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::Glacier2::SSLPermissionsVerifier', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Glacier2::SSLPermissionsVerifier', $facet);
        }

        public static function ice_staticId()
        {
            return '::Glacier2::SSLPermissionsVerifier';
        }
    }

    $Glacier2__t_SSLPermissionsVerifier = IcePHP_defineClass('::Glacier2::SSLPermissionsVerifier', 'Glacier2_SSLPermissionsVerifier', -1, true, false, $Ice__t_Object, null, null);

    $Glacier2__t_SSLPermissionsVerifierPrx = IcePHP_defineProxy($Glacier2__t_SSLPermissionsVerifier);

    IcePHP_defineOperation($Glacier2__t_SSLPermissionsVerifier, 'authorize', 2, 1, 2, array(array($Glacier2__t_SSLInfo, false, 0)), array(array($IcePHP__t_string, false, 0)), array($IcePHP__t_bool, false, 0), array($Glacier2__t_PermissionDeniedException));
}
?>
