<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `samples.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $sooh_services_samples__t_sample0000;
global $sooh_services_samples__t_sample0000Prx;
global $IcePHP__t_string;
if(!interface_exists('sooh_services_samples_sample0000',false))
{
    interface sooh_services_samples_sample0000 extends Ice_Object
    {
        public function sayhi($who);
        public function echohi($who);
        public function forwardAsy($serviceClass, $serviceFunc, $jsonedArray);
        public function forwardSyn($serviceClass, $serviceFunc, $jsonedArray);
    }

    class sooh_services_samples_sample0000PrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::sooh::services::samples::sample0000', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::sooh::services::samples::sample0000', $facet);
        }

        public static function ice_staticId()
        {
            return '::sooh::services::samples::sample0000';
        }
    }

    $sooh_services_samples__t_sample0000 = IcePHP_defineClass('::sooh::services::samples::sample0000', 'sooh_services_samples_sample0000', -1, true, false, $Ice__t_Object, null, null);

    $sooh_services_samples__t_sample0000Prx = IcePHP_defineProxy($sooh_services_samples__t_sample0000);

    IcePHP_defineOperation($sooh_services_samples__t_sample0000, 'sayhi', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_samples__t_sample0000, 'echohi', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_string, false, 0), null);
    IcePHP_defineOperation($sooh_services_samples__t_sample0000, 'forwardAsy', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_samples__t_sample0000, 'forwardSyn', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_string, false, 0), null);
}
?>
