// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `evtcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.evtcenter;

public interface triggersPrx extends Ice.ObjectPrx
{
    public void onRegister(String data);

    public void onRegister(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onRegister(String data);

    public Ice.AsyncResult begin_onRegister(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onRegister(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onRegister(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onRegister(String data, Callback_triggers_onRegister __cb);

    public Ice.AsyncResult begin_onRegister(String data, java.util.Map<String, String> __ctx, Callback_triggers_onRegister __cb);

    public Ice.AsyncResult begin_onRegister(String data, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onRegister(String data, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onRegister(String data, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onRegister(String data, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_onRegister(Ice.AsyncResult __result);

    public void onLogout(String data);

    public void onLogout(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onLogout(String data);

    public Ice.AsyncResult begin_onLogout(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onLogout(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onLogout(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onLogout(String data, Callback_triggers_onLogout __cb);

    public Ice.AsyncResult begin_onLogout(String data, java.util.Map<String, String> __ctx, Callback_triggers_onLogout __cb);

    public Ice.AsyncResult begin_onLogout(String data, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onLogout(String data, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onLogout(String data, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onLogout(String data, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_onLogout(Ice.AsyncResult __result);

    public void onLogin(String data);

    public void onLogin(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onLogin(String data);

    public Ice.AsyncResult begin_onLogin(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onLogin(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onLogin(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onLogin(String data, Callback_triggers_onLogin __cb);

    public Ice.AsyncResult begin_onLogin(String data, java.util.Map<String, String> __ctx, Callback_triggers_onLogin __cb);

    public Ice.AsyncResult begin_onLogin(String data, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onLogin(String data, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onLogin(String data, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onLogin(String data, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_onLogin(Ice.AsyncResult __result);

    public void onBuyRequest(String data);

    public void onBuyRequest(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onBuyRequest(String data);

    public Ice.AsyncResult begin_onBuyRequest(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onBuyRequest(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onBuyRequest(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onBuyRequest(String data, Callback_triggers_onBuyRequest __cb);

    public Ice.AsyncResult begin_onBuyRequest(String data, java.util.Map<String, String> __ctx, Callback_triggers_onBuyRequest __cb);

    public Ice.AsyncResult begin_onBuyRequest(String data, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onBuyRequest(String data, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onBuyRequest(String data, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onBuyRequest(String data, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public void end_onBuyRequest(Ice.AsyncResult __result);

    public void onBuyConfirm(String data);

    public void onBuyConfirm(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onBuyConfirm(String data);

    public Ice.AsyncResult begin_onBuyConfirm(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onBuyConfirm(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onBuyConfirm(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onBuyConfirm(String data, Callback_triggers_onBuyConfirm __cb);

    public Ice.AsyncResult begin_onBuyConfirm(String data, java.util.Map<String, String> __ctx, Callback_triggers_onBuyConfirm __cb);

    public Ice.AsyncResult begin_onBuyConfirm(String data, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onBuyConfirm(String data, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onBuyConfirm(String data, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onBuyConfirm(String data, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public void end_onBuyConfirm(Ice.AsyncResult __result);

    public void onRechargeRequest(String data);

    public void onRechargeRequest(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onRechargeRequest(String data);

    public Ice.AsyncResult begin_onRechargeRequest(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onRechargeRequest(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onRechargeRequest(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onRechargeRequest(String data, Callback_triggers_onRechargeRequest __cb);

    public Ice.AsyncResult begin_onRechargeRequest(String data, java.util.Map<String, String> __ctx, Callback_triggers_onRechargeRequest __cb);

    public Ice.AsyncResult begin_onRechargeRequest(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onRechargeRequest(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onRechargeRequest(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onRechargeRequest(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public void end_onRechargeRequest(Ice.AsyncResult __result);

    public void onRechargeConfirm(String data);

    public void onRechargeConfirm(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onRechargeConfirm(String data);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, Callback_triggers_onRechargeConfirm __cb);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, java.util.Map<String, String> __ctx, Callback_triggers_onRechargeConfirm __cb);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onRechargeConfirm(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public void end_onRechargeConfirm(Ice.AsyncResult __result);

    public void onWithdrawRequest(String data);

    public void onWithdrawRequest(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWithdrawRequest(String data);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, Callback_triggers_onWithdrawRequest __cb);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, java.util.Map<String, String> __ctx, Callback_triggers_onWithdrawRequest __cb);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWithdrawRequest(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public void end_onWithdrawRequest(Ice.AsyncResult __result);

    public void onWithdrawConfirm(String data);

    public void onWithdrawConfirm(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, Callback_triggers_onWithdrawConfirm __cb);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, java.util.Map<String, String> __ctx, Callback_triggers_onWithdrawConfirm __cb);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWithdrawConfirm(String data, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public void end_onWithdrawConfirm(Ice.AsyncResult __result);

    public void onWaresFull(String data);

    public void onWaresFull(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWaresFull(String data);

    public Ice.AsyncResult begin_onWaresFull(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWaresFull(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWaresFull(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWaresFull(String data, Callback_triggers_onWaresFull __cb);

    public Ice.AsyncResult begin_onWaresFull(String data, java.util.Map<String, String> __ctx, Callback_triggers_onWaresFull __cb);

    public Ice.AsyncResult begin_onWaresFull(String data, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWaresFull(String data, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onWaresFull(String data, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWaresFull(String data, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public void end_onWaresFull(Ice.AsyncResult __result);

    public void onWaresMonthly(String data);

    public void onWaresMonthly(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWaresMonthly(String data);

    public Ice.AsyncResult begin_onWaresMonthly(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWaresMonthly(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWaresMonthly(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWaresMonthly(String data, Callback_triggers_onWaresMonthly __cb);

    public Ice.AsyncResult begin_onWaresMonthly(String data, java.util.Map<String, String> __ctx, Callback_triggers_onWaresMonthly __cb);

    public Ice.AsyncResult begin_onWaresMonthly(String data, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWaresMonthly(String data, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onWaresMonthly(String data, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWaresMonthly(String data, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public void end_onWaresMonthly(Ice.AsyncResult __result);

    public void onWaresEnd(String data);

    public void onWaresEnd(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWaresEnd(String data);

    public Ice.AsyncResult begin_onWaresEnd(String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onWaresEnd(String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWaresEnd(String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onWaresEnd(String data, Callback_triggers_onWaresEnd __cb);

    public Ice.AsyncResult begin_onWaresEnd(String data, java.util.Map<String, String> __ctx, Callback_triggers_onWaresEnd __cb);

    public Ice.AsyncResult begin_onWaresEnd(String data, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWaresEnd(String data, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onWaresEnd(String data, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onWaresEnd(String data, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_onWaresEnd(Ice.AsyncResult __result);

    public void onCustomEvt(String evt, String data);

    public void onCustomEvt(String evt, String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onCustomEvt(String evt, String data);

    public Ice.AsyncResult begin_onCustomEvt(String evt, String data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_onCustomEvt(String evt, String data, Ice.Callback __cb);

    public Ice.AsyncResult begin_onCustomEvt(String evt, String data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_onCustomEvt(String evt, String data, Callback_triggers_onCustomEvt __cb);

    public Ice.AsyncResult begin_onCustomEvt(String evt, String data, java.util.Map<String, String> __ctx, Callback_triggers_onCustomEvt __cb);

    public Ice.AsyncResult begin_onCustomEvt(String evt, 
                                             String data, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onCustomEvt(String evt, 
                                             String data, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_onCustomEvt(String evt, 
                                             String data, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_onCustomEvt(String evt, 
                                             String data, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public void end_onCustomEvt(Ice.AsyncResult __result);
}
