<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'jpush' => array($vendorDir . '/jpush/jpush/src'),
    'Sooh\\' => array($vendorDir . '/hillstill/sooh/src'),
    'SoohYaf\\' => array($vendorDir . '/hillstill/sooh-yaf/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Httpful' => array($vendorDir . '/nategood/httpful/src'),
);
