<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `BuiltinSequences.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_BoolSeq;

if(!isset($Ice__t_BoolSeq))
{
    $Ice__t_BoolSeq = IcePHP_defineSequence('::Ice::BoolSeq', $IcePHP__t_bool);
}

global $Ice__t_ByteSeq;

if(!isset($Ice__t_ByteSeq))
{
    $Ice__t_ByteSeq = IcePHP_defineSequence('::Ice::ByteSeq', $IcePHP__t_byte);
}

global $Ice__t_ShortSeq;

if(!isset($Ice__t_ShortSeq))
{
    $Ice__t_ShortSeq = IcePHP_defineSequence('::Ice::ShortSeq', $IcePHP__t_short);
}

global $Ice__t_IntSeq;

if(!isset($Ice__t_IntSeq))
{
    $Ice__t_IntSeq = IcePHP_defineSequence('::Ice::IntSeq', $IcePHP__t_int);
}

global $Ice__t_LongSeq;

if(!isset($Ice__t_LongSeq))
{
    $Ice__t_LongSeq = IcePHP_defineSequence('::Ice::LongSeq', $IcePHP__t_long);
}

global $Ice__t_FloatSeq;

if(!isset($Ice__t_FloatSeq))
{
    $Ice__t_FloatSeq = IcePHP_defineSequence('::Ice::FloatSeq', $IcePHP__t_float);
}

global $Ice__t_DoubleSeq;

if(!isset($Ice__t_DoubleSeq))
{
    $Ice__t_DoubleSeq = IcePHP_defineSequence('::Ice::DoubleSeq', $IcePHP__t_double);
}

global $Ice__t_StringSeq;

if(!isset($Ice__t_StringSeq))
{
    $Ice__t_StringSeq = IcePHP_defineSequence('::Ice::StringSeq', $IcePHP__t_string);
}

global $Ice__t_ObjectSeq;

if(!isset($Ice__t_ObjectSeq))
{
    $Ice__t_ObjectSeq = IcePHP_defineSequence('::Ice::ObjectSeq', $Ice__t_Object);
}

global $Ice__t_ObjectProxySeq;

if(!isset($Ice__t_ObjectProxySeq))
{
    $Ice__t_ObjectProxySeq = IcePHP_defineSequence('::Ice::ObjectProxySeq', $Ice__t_ObjectPrx);
}
?>
