<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `ConnectionF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_ConnectionInfo;
if(!isset($Ice__t_ConnectionInfo))
{
    $Ice__t_ConnectionInfo = IcePHP_declareClass('::Ice::ConnectionInfo');
}

global $Ice__t_WSConnectionInfo;
if(!isset($Ice__t_WSConnectionInfo))
{
    $Ice__t_WSConnectionInfo = IcePHP_declareClass('::Ice::WSConnectionInfo');
}

global $Ice__t_Connection;
if(!isset($Ice__t_Connection))
{
    $Ice__t_Connection = IcePHP_declareClass('::Ice::Connection');
}
?>
