<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `LoggerF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_Logger;
if(!isset($Ice__t_Logger))
{
    $Ice__t_Logger = IcePHP_declareClass('::Ice::Logger');
}
?>
