<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `ObjectFactoryF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_ObjectFactory;
if(!isset($Ice__t_ObjectFactory))
{
    $Ice__t_ObjectFactory = IcePHP_declareClass('::Ice::ObjectFactory');
}
?>
