<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `ObjectFactory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_ObjectFactory;

if(!interface_exists('Ice_ObjectFactory',false))
{
    interface Ice_ObjectFactory
    {
        public function create($type);
        public function destroy();
    }

    $Ice__t_ObjectFactory = IcePHP_defineClass('::Ice::ObjectFactory', 'Ice_ObjectFactory', -1, true, false, $Ice__t_Object, null, null);
}
?>
