<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `PluginF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_Plugin;
if(!isset($Ice__t_Plugin))
{
    $Ice__t_Plugin = IcePHP_declareClass('::Ice::Plugin');
}

global $Ice__t_PluginManager;
if(!isset($Ice__t_PluginManager))
{
    $Ice__t_PluginManager = IcePHP_declareClass('::Ice::PluginManager');
}
?>
