<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `SliceChecksumDict.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_SliceChecksumDict;

if(!isset($Ice__t_SliceChecksumDict))
{
    $Ice__t_SliceChecksumDict = IcePHP_defineDictionary('::Ice::SliceChecksumDict', $IcePHP__t_string, $IcePHP__t_string);
}
?>
