// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `msgcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.msgcenter;

public interface _bypushOperations
{
    /**
     * 全平台发送推送消息，receivers是逗号分隔的用户id列表
     * @param __current The Current object for the invocation.
     **/
    void sendMsg(String receivers, String msg, Ice.Current __current);

    /**
     * 全平台发送推送命令，receivers是逗号分隔的用户id列表
     * @param __current The Current object for the invocation.
     **/
    void sendCmd(String receivers, String cmd, Ice.Current __current);
}
