<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `logcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $sooh_services_logcenter__t_loger;
global $sooh_services_logcenter__t_logerPrx;
global $IcePHP__t_string;
if(!interface_exists('sooh_services_logcenter_loger',false))
{
    interface sooh_services_logcenter_loger extends Ice_Object
    {
        public function writeSyn($logdata, $reqdata);
        public function writeAsy($logdata, $reqdata);
    }

    class sooh_services_logcenter_logerPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::sooh::services::logcenter::loger', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::sooh::services::logcenter::loger', $facet);
        }

        public static function ice_staticId()
        {
            return '::sooh::services::logcenter::loger';
        }
    }
    $sooh_services_logcenter__t_loger = IcePHP_defineClass('::sooh::services::logcenter::loger', 'sooh_services_logcenter_loger', -1, true, false, $Ice__t_Object, null, null);
    $sooh_services_logcenter__t_logerPrx = IcePHP_defineProxy($sooh_services_logcenter__t_loger);
    IcePHP_defineOperation($sooh_services_logcenter__t_loger, 'writeSyn', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_string, false, 0), null);
    IcePHP_defineOperation($sooh_services_logcenter__t_loger, 'writeAsy', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);
}
?>
