<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `msgcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

global $IcePHP__t_string;
global $sooh_services_msgcenter__t_bysms;
global $sooh_services_msgcenter__t_bysmsPrx;

if(!interface_exists('sooh_services_msgcenter_bysms',false))
{
    interface sooh_services_msgcenter_bysms extends Ice_Object
    {
        public function sendCode($receiver, $msg);
        public function sendNotice($receivers, $msg);
        public function sendMarket($receivers, $msg);
    }

    class sooh_services_msgcenter_bysmsPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::sooh::services::msgcenter::bysms', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::sooh::services::msgcenter::bysms', $facet);
        }

        public static function ice_staticId()
        {
            return '::sooh::services::msgcenter::bysms';
        }
    }
    $sooh_services_msgcenter__t_bysms = IcePHP_defineClass('::sooh::services::msgcenter::bysms', 'sooh_services_msgcenter_bysms', -1, true, false, $Ice__t_Object, null, null);
    $sooh_services_msgcenter__t_bysmsPrx = IcePHP_defineProxy($sooh_services_msgcenter__t_bysms);
    IcePHP_defineOperation($sooh_services_msgcenter__t_bysms, 'sendCode', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_msgcenter__t_bysms, 'sendNotice', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_msgcenter__t_bysms, 'sendMarket', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);

}

global $sooh_services_msgcenter__t_bypush;
global $sooh_services_msgcenter__t_bypushPrx;

if(!interface_exists('sooh_services_msgcenter_bypush',false))
{
    interface sooh_services_msgcenter_bypush extends Ice_Object
    {
        public function sendMsg($receivers, $msg);
        public function sendCmd($receivers, $cmd);
    }

    class sooh_services_msgcenter_bypushPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::sooh::services::msgcenter::bypush', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::sooh::services::msgcenter::bypush', $facet);
        }

        public static function ice_staticId()
        {
            return '::sooh::services::msgcenter::bypush';
        }
    }

    $sooh_services_msgcenter__t_bypush = IcePHP_defineClass('::sooh::services::msgcenter::bypush', 'sooh_services_msgcenter_bypush', -1, true, false, $Ice__t_Object, null, null);

    $sooh_services_msgcenter__t_bypushPrx = IcePHP_defineProxy($sooh_services_msgcenter__t_bypush);

    IcePHP_defineOperation($sooh_services_msgcenter__t_bypush, 'sendMsg', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_msgcenter__t_bypush, 'sendCmd', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);
}
?>
