// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `samples.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.samples;

public interface sample0000 extends Ice.Object,
                                    _sample0000Operations, _sample0000OperationsNC
{
    public static final String ice_staticId = "::sooh::services::samples::sample0000";

    public static final long serialVersionUID = -2323780742764289509L;
}
