
<div class="bjui-pageHeader">
	<?php
	$url = \Sooh\Base\Tools::uri(array('__EXCEL__' => 1), 'voucherindex');
	echo '<form action="'.$url.'" method="post" id="wares-exportChecked_1" style="display: none;"></form>';
	//$renderer = new \Prj\Misc\FormRenderer;
	//echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
	$renderer = new \Prj\Misc\FormRenderer;
	$formPart = $renderer->getSearchStandard_parts(\Sooh\Base\Form\Broker::getCopy('default'), '<label>领取时间从:</label>');
	echo $formPart[0];
	?>
<div class="pull-right">
		<div class="btn-group">
			<button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">
				复选框-批量操作<span class="caret"></span></button>
			<ul class="dropdown-menu right" role="menu">
				<li>
					<a href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__' => 1, 'where' => $this->where), 'voucherindex'); ?>">导出全部</a>
				</li>
				<li><a class="wares-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>
				<!--
                        <li class="divider"></li>
                        <li><?php echo \Prj\Misc\View::btnDelChooseInDatagrid('xxx'); ?></li>
                        -->
			</ul>
		</div>
		<script>
			/*
			 构造表单 post 方法 提交
			 */
			var ids = new Array();
			$('.wares-export').click(function () {
				if (ids.length == 0) {
					$(document).alertmsg('error', '无选中选项');
					return false;
				}
				$('#wares-exportChecked').html('');
				for (var i in ids) {
					var reg = /function[.]*/;
					if (reg.exec(ids[i]) != null) {
						continue;
					}
					$('#wares-exportChecked').append("<input type='hidden' name='ids[]' value='" + ids[i] + "'>");
				}
				$('#wares-exportChecked').submit();
				//window.location.href="/index.php?__=manage/managers/index&__EXCEL__=1&ids="+ids;
				return false;
			});
		</script>
	</div>
	<?php
		echo  $formPart[1].'</form></div>';
	?>
</div>
<div class="bjui-pageContent tableContent">
	<table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true"
	       data-toggle="tablefixed">
		<thead>
		<tr><?php
			$header = $this->header;
			foreach ($header as $k => $v) {
				echo "<th width = '" . $v . "'>";
				echo $k;
				echo "</th>";
			}
			?>
			<th width="10"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
			<th width="40">操作</th>
		</tr>
		</thead>
		<tbody>
		<?php
		$rs = $this->rs;
		if (!empty($rs)) {
			foreach ($rs as $r) {
				$_pkey_ = $r['_pkey_val_'];
				$status = $r['status'];
				unset($r['status']);
				echo "<tr data-id=\"{$_pkey_}\">";
				unset($r['_pkey_val_']);
				foreach ($r as $k => $v) {
					echo "<td>";
					echo $v;
					echo "</td>";
				}
				echo '<td><input type="checkbox" name="ids" data-group="ids" data-toggle="icheck" value="' . $_pkey_ . '"></td>';
				echo "<td>";
				if ($status == \Prj\Consts\Voucher::status_unuse) {
					echo '<a href="' . \Sooh\Base\Tools::uri(['_pkey_val_' => $_pkey_], 'voucherabandon') . '" class="btn
						btn-red" data-toggle="doajax"
						data-confirm-msg="确定要禁用该券吗？">禁用</a>';
				} elseif ($status == \Prj\Consts\Voucher::status_abandon) {
					echo '<a href="' . \Sooh\Base\Tools::uri(['_pkey_val_' => $_pkey_], 'voucherunuse') . '" class="btn
						btn-green" data-toggle="doajax"
						data-confirm-msg="确定要恢复该券可用么吗？">启用</a>';
				}
				echo "</td>";
				echo "</tr>";
			}
		}
		?>
		</tbody>
	</table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>
