<div class="bjui-pageContent">
    <?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getEditStandard(\Sooh\Base\Form\Broker::getCopy('default'),2);
    ?>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close" data-icon="close">取消</button></li>
        <?php $doit = '发送'; ?>
        <li><button type="submit" class="btn-green" data-icon="save"><?php echo $doit; ?></button></li>
    </ul>
</div>