<?php $randNum = rand(1000,9999); ?>
<div class="bjui-pageHeader">
    <div style="color: red;padding: 10px;">
        说明:用于查询单个用户的资金流水情况.
    </div>
    <?php
    $renderer = new \Prj\Misc\FormRenderer;
    $randNum = rand(1000,9999);
    echo $renderer->formForExport(Sooh\Base\Tools::uri([],'index'),$randNum);
    // echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));

    echo  $renderer->getSearchStandard(
        \Sooh\Base\Form\Broker::getCopy('default'),
        $renderer->getBatchArea('', \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'tally'), null,false)
    );
    ?>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true"
           data-toggle="tablefixed">
        <thead>
        <tr><?php
            $header = $this->header;
            if(!empty($header))
            {
                foreach ($header as $k => $v) {
                    echo "<th width = '" . $v . "'>";
                    echo $k;
                    echo "</th>";
                }
            }

            ?>
            <th width="30"><?php echo \Prj\Misc\View::thCheckBox(); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        $rs = $this->rs;
        if (!empty($rs)) {
            foreach ($rs as $r) {
                echo "<tr>";
                foreach ($r as $k => $v) {
                    if($k=='nAdd' && $r['nAdd']>=0){
                        echo "<td style='color: red'>";
                    }elseif($k=='nAdd' && $r['nAdd']<=0){
                        echo "<td style='color: green'>";
                    }else{
                        echo "<td>";
                    }

                    echo $v;
                    echo "</td>";
                }
                echo '<td>'.\Prj\Misc\View::trCheckBox().'</td>';
                echo "</tr>";
            }
        }
        ?>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>