// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `samples.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.samples;

public final class sample0000PrxHolder
{
    public
    sample0000PrxHolder()
    {
    }

    public
    sample0000PrxHolder(sample0000Prx value)
    {
        this.value = value;
    }

    public sample0000Prx value;
}
