<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `evtcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

global $IcePHP__t_string;
global $sooh_services_evtcenter__t_triggers;
global $sooh_services_evtcenter__t_triggersPrx;

if(!interface_exists('sooh_services_evtcenter_triggers',false))
{
    interface sooh_services_evtcenter_triggers extends Ice_Object
    {
        public function onRegister($data);
        public function onLogout($data);
        public function onLogin($data);
        public function onBuyRequest($data);
        public function onBuyConfirm($data);
        public function onRechargeRequest($data);
        public function onRechargeConfirm($data);
        public function onWithdrawRequest($data);
        public function onWithdrawConfirm($data);
        public function onWaresFull($data);
        public function onWaresMonthly($data);
        public function onWaresEnd($data);
        public function onCustomEvt($evt, $data);
    }

    class sooh_services_evtcenter_triggersPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::sooh::services::evtcenter::triggers', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::sooh::services::evtcenter::triggers', $facet);
        }

        public static function ice_staticId()
        {
            return '::sooh::services::evtcenter::triggers';
        }
    }

    $sooh_services_evtcenter__t_triggers = IcePHP_defineClass('::sooh::services::evtcenter::triggers', 'sooh_services_evtcenter_triggers', -1, true, false, $Ice__t_Object, null, null);

    $sooh_services_evtcenter__t_triggersPrx = IcePHP_defineProxy($sooh_services_evtcenter__t_triggers);

    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onRegister', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onLogout', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onLogin', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onBuyRequest', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onBuyConfirm', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onRechargeRequest', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onRechargeConfirm', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onWithdrawRequest', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onWithdrawConfirm', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onWaresFull', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onWaresMonthly', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onWaresEnd', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, null, null);
    IcePHP_defineOperation($sooh_services_evtcenter__t_triggers, 'onCustomEvt', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, null, null);
}
?>
