<div class="bjui-pageHeader">
    <?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'),
        '&nbsp;'.\Prj\Misc\View::btnAjax('补还款计划',\Sooh\Base\Tools::uri(['addInterestSub'=>1],'subInterestFix'),'确定补还款计划?').
        '&nbsp;'.\Prj\Misc\View::btnAjax('补发贴息金额',\Sooh\Base\Tools::uri(['sendInterestSub'=>1],'subInterestFix'),'确定补发贴息金额?')
    );
    ?>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true"
           data-toggle="tablefixed">
        <thead>
        <tr><?php
            $header = $this->header;
            if(!empty($header))
            {
                foreach ($header as $k => $v) {
                    echo "<th width = '" . $v[1] . "'>";
                    echo $v[0];
                    echo "</th>";
                }
            }

            ?>
            <th width="30"><?php echo \Prj\Misc\View::thCheckBox(); ?></th>
            <th width="100">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $rs = $this->rs;
        if (!empty($rs)) {
            foreach ($rs as $r) {
                echo "<tr>";
                foreach ($r as $k => $v) {
                    echo "<td>";
                    echo $v;
                    echo "</td>";
                }
                echo '<td>'.\Prj\Misc\View::trCheckBox().'</td>';
                echo "<td>";
                reset($r);
                $_pkey_val_ = \Prj\Misc\View::encodePkey(['id'=>current($r)]);
                //echo \Prj\Misc\View::btnEditInDatagrid('编辑',Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_val_],'edit'));
                echo "</td>";
                echo "</tr>";
            }
        }
        ?>
        </tbody>
    </table>
</div>
