<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `EndpointF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice__t_EndpointInfo;
if(!isset($Ice__t_EndpointInfo))
{
    $Ice__t_EndpointInfo = IcePHP_declareClass('::Ice::EndpointInfo');
}

global $Ice__t_IPEndpointInfo;
if(!isset($Ice__t_IPEndpointInfo))
{
    $Ice__t_IPEndpointInfo = IcePHP_declareClass('::Ice::IPEndpointInfo');
}

global $Ice__t_TCPEndpointInfo;
if(!isset($Ice__t_TCPEndpointInfo))
{
    $Ice__t_TCPEndpointInfo = IcePHP_declareClass('::Ice::TCPEndpointInfo');
}

global $Ice__t_UDPEndpointInfo;
if(!isset($Ice__t_UDPEndpointInfo))
{
    $Ice__t_UDPEndpointInfo = IcePHP_declareClass('::Ice::UDPEndpointInfo');
}

global $Ice__t_WSEndpointInfo;
if(!isset($Ice__t_WSEndpointInfo))
{
    $Ice__t_WSEndpointInfo = IcePHP_declareClass('::Ice::WSEndpointInfo');
}

global $Ice__t_Endpoint;
if(!isset($Ice__t_Endpoint))
{
    $Ice__t_Endpoint = IcePHP_declareClass('::Ice::Endpoint');
}

global $Ice__t_EndpointSeq;

if(!isset($Ice__t_EndpointSeq))
{
    $Ice__t_EndpointSeq = IcePHP_defineSequence('::Ice::EndpointSeq', $Ice__t_Endpoint);
}
?>
