<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__' => 1), 'mineMsg'); ?>" method="post"
      id="wares-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader">
	<?php
	$renderer = new \Prj\Misc\FormRenderer;
	echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
	?>
	<lable>手机号：</lable>
        <input id="phone" type="text" name="phone" value="<?php echo $this->phone; ?>" />
        <button type="button" class="btn btn-default" onclick="openMydialog(this)">查询用户ID</button>
	<div class="pull-right">
		<div class="btn-group">
			<button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">
				复选框-批量操作<span class="caret"></span></button>
			<ul class="dropdown-menu right" role="menu">
				<li>
					<a href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__' => 1, 'where' => $this->where), 'mineMsg'); ?>">导出全部</a>
				</li>
				<li><a class="wares-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>
				<?php echo \Prj\Misc\View::btnDelChooseInDatagrid('xxx'); ?>
			</ul>
		</div>
		<script>
			/*
			 构造表单 post 方法 提交
			 */
			var ids = new Array();
			$('.wares-export').click(function () {
				if (ids.length == 0) {
					$(document).alertmsg('error', '无选中选项');
					return false;
				}
				$('#wares-exportChecked').html('');
				for (var i in ids) {
					var reg = /function[.]*/;
					if (reg.exec(ids[i]) != null) {
						continue;
					}
					$('#wares-exportChecked').append("<input type='hidden' name='ids[]' value='" + ids[i] + "'>");
				}
				$('#wares-exportChecked').submit();
				return false;
			});

			function openMydialog(obj) {
            	var phone=$('#phone').val();
            	$(obj).dialog({id:'mydialog', url:'<?php echo \Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_],'phone'); ?>phone='+phone, title:'用户ID'});
        	}
		</script>
	</div>
</div>
<div class="bjui-pageContent tableContent">
	<table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true"
	       data-toggle="tablefixed">
		<thead>
		<tr><?php
			$header = $this->header;
			foreach ($header as $k => $v) {
				echo "<th width = '" . $v . "'>";
				echo $k;
				echo "</th>";
			}
			?>
			<th width="10"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
		</tr>
		</thead>
		<tbody>
		<?php
		$rs = $this->rs;
		if (!empty($rs)) {
			foreach ($rs as $r) {
				$_pkey_ = $r['_pkey_val_'];
				echo "<tr data-id=\"{$_pkey_}\">";
				unset($r['_pkey_val_']);
				foreach ($r as $k => $v) {
					echo "<td>";
					echo $v;
					echo "</td>";
				}
				echo '<td><input type="checkbox" name="ids" data-group="ids" data-toggle="icheck" value="' . $_pkey_ . '"></td>';
				echo "</tr>";
			}
		}
		?>
		</tbody>
	</table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>