// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `samples.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.samples;

public interface sample0000Prx extends Ice.ObjectPrx
{
    public void sayhi(String who);

    public void sayhi(String who, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sayhi(String who);

    public Ice.AsyncResult begin_sayhi(String who, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sayhi(String who, Ice.Callback __cb);

    public Ice.AsyncResult begin_sayhi(String who, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sayhi(String who, Callback_sample0000_sayhi __cb);

    public Ice.AsyncResult begin_sayhi(String who, java.util.Map<String, String> __ctx, Callback_sample0000_sayhi __cb);

    public Ice.AsyncResult begin_sayhi(String who, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sayhi(String who, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sayhi(String who, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sayhi(String who, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_sayhi(Ice.AsyncResult __result);

    public String echohi(String who);

    public String echohi(String who, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_echohi(String who);

    public Ice.AsyncResult begin_echohi(String who, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_echohi(String who, Ice.Callback __cb);

    public Ice.AsyncResult begin_echohi(String who, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_echohi(String who, Callback_sample0000_echohi __cb);

    public Ice.AsyncResult begin_echohi(String who, java.util.Map<String, String> __ctx, Callback_sample0000_echohi __cb);

    public Ice.AsyncResult begin_echohi(String who, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_echohi(String who, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_echohi(String who, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_echohi(String who, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public String end_echohi(Ice.AsyncResult __result);

    public void forwardAsy(String serviceClass, String serviceFunc, String jsonedArray);

    public void forwardAsy(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, String serviceFunc, String jsonedArray);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, String serviceFunc, String jsonedArray, Ice.Callback __cb);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, String serviceFunc, String jsonedArray, Callback_sample0000_forwardAsy __cb);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx, Callback_sample0000_forwardAsy __cb);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forwardAsy(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_forwardAsy(Ice.AsyncResult __result);

    public String forwardSyn(String serviceClass, String serviceFunc, String jsonedArray);

    public String forwardSyn(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, String serviceFunc, String jsonedArray);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, String serviceFunc, String jsonedArray, Ice.Callback __cb);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, String serviceFunc, String jsonedArray, Callback_sample0000_forwardSyn __cb);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, String serviceFunc, String jsonedArray, java.util.Map<String, String> __ctx, Callback_sample0000_forwardSyn __cb);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forwardSyn(String serviceClass, 
                                            String serviceFunc, 
                                            String jsonedArray, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public String end_forwardSyn(Ice.AsyncResult __result);
}
