<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Properties.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once __DIR__.'/../Ice/PropertiesAdmin.php';

global $Ice__t_Properties;

if(!interface_exists('Ice_Properties',false))
{
    interface Ice_Properties
    {
        public function getProperty($key);
        public function getPropertyWithDefault($key, $value);
        public function getPropertyAsInt($key);
        public function getPropertyAsIntWithDefault($key, $value);
        public function getPropertyAsList($key);
        public function getPropertyAsListWithDefault($key, $value);
        public function getPropertiesForPrefix($prefix);
        public function setProperty($key, $value);
        public function getCommandLineOptions();
        public function parseCommandLineOptions($prefix, $options);
        public function parseIceCommandLineOptions($options);
        public function load($file);
        public function _clone();
    }

    $Ice__t_Properties = IcePHP_defineClass('::Ice::Properties', 'Ice_Properties', -1, true, false, $Ice__t_Object, null, null);
}
?>
