<script src="/js/common/checked.js"></script>
<div class="bjui-pageHeader" >
    <?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getSearchStandard_without_endTag_form_div(\Sooh\Base\Form\Broker::getCopy('default'));
    echo '</form>';
    ?>
    <?php
    \Prj\Misc\View::exportBox(\Sooh\Base\Tools::uri(array('__EXCEL__' => 'all', 'where' => $this->where), 'downExcel'), \Sooh\Base\Tools::uri(array('__EXCEL__' => 'select'), 'downExcel'));
    ?>
</div>

</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>
            <tr><?php
                $headers = $this->headers;
                foreach ($headers as $k => $v) {
                    echo "<th width=\"$v\">$k</th>"; //data-order-field="operation" align="center"
                }
                ?>
                <!--<th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>-->
                <th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($this->records)) {
                foreach ($this->records as $r) {
                    $_pkey_val_ = $r['userId'];
                    ?>
                    <tr data-id="<?= $_pkey_val_ ?>">
                        <td><?= $r['userId'] ?></td>
                        <td><?= $r['taskNumber'] ?></td>
                        <td><?= \Prj\Misc\View::fmtYmd($r['ymdFirst']) ?></td>
                        <td><?= $r['investmentScore'] ?></td>
                        <td><?= $r['shareVoucherScore'] ?></td>
                        <td><?= $r['checkinScore'] ?></td>
                        <td><?= $r['inviteScore'] ?></td>
                        <td><?= $r['friendsInvestmentScore'] ?></td>
                        <td><?= $r['totalScore'] ?></td>
                        <td><?= $r['rewards'] ?></td>
                        <td><?= \Prj\Misc\View::trCheckBox($_pkey_val_) ?></td>
                    </tr>
                    <?php
                }
            }
            ?>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager); ?></div>
