<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1),'index'); ?>" method="post" id="wares-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader">
    <?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
    ?>
    <div class="pull-right">
        <script>
            /*
             构造表单 post 方法 提交
             */
            var ids = new Array();
            $('.wares-export').click(function(){
                if(ids.length==0)
                {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#wares-exportChecked').html('');
                for(var i in ids)
                {
                    var reg = /function[.]*/;
                    if(reg.exec(ids[i])!=null)
                    {
                        continue;
                    }
                    $('#wares-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                }
                $('#wares-exportChecked').submit();
                return false;
            });
        </script>
    </div>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>
        <tr><?php
            $headers = $this->headers;
            foreach($headers as $k=>$v){
                echo "<th width=\"".$v."\" >".$k."</th>";
            }

            ?>
            <th width="30"><?php echo \Prj\Misc\View::thCheckBox(); ?></th>
            <th width="300">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $records = $this->rs;
        if(!empty($records)){
            foreach($records as $r){
                echo "<tr>";
                foreach($r as $v)
                {
                    echo "<td>";
                    echo $v;
                    echo "</td>";
                }
                echo "<td>";
                reset($r);
                $pkey = \Prj\Misc\View::encodePkey([
                    'id'=>current($r),
                ]);
                echo \Prj\Misc\View::trCheckBox($pkey);
                echo "</td>";
                echo "<td>";
                echo \Prj\Misc\View::btnDefaultInDatagrid('修改标的模板',\Sooh\Base\Tools::uri(['_pkey_val_'=>$pkey],'edit'));
                echo " ";
                echo \Prj\Misc\View::btnAjax('删除',\Sooh\Base\Tools::uri(['_pkey_val_'=>$pkey],'delete'));
                echo "</td>";
                echo "</tr>";
            }
        }
        ?>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>
