
<div class="bjui-pageHeader"><?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
    ?>
    <div class="pull-right">

        <div class="btn-group">
            <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">批量操作<span class="caret"></span></button>
            <ul class="dropdown-menu right" role="menu">
                <li><a  href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'userredpacketdaily'); ?>">导出全部</a></li>
            </ul>
        </div>
        <script>
            /*
             构造表单 post 方法 提交
             */
            var ids = new Array();
            $('.contracts-export').click(function(){
                if(ids.length==0)
                {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#contracts-exportChecked').html(''); //add ' '
                for(var i in ids)
                {
                    var reg = /function[.]*/;
                    if(reg.exec(ids[i])!=null)
                    {
                        continue;
                    }
                    $('#contracts-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                }
                $('#contracts-exportChecked').submit();
                return false;
            });
        </script>
    </div>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>
        <tr>
            <?php $headers=$this->headers;
            foreach($headers as $k=>$v){
                echo "<th width=\"$v\">$k</th>";
            }
            ?>
        </tr>
        </thead>
        <tbody>
        <?php $records=$this->records;
        if (!empty($records)){
            foreach ($records as $r){
                $_pkey_ = $r['_pkey_'];
                echo "<tr data-id=\"{$_pkey_}\">";
                unset ($r['_pkey_']);
                echo '<td>'.implode('</td><td>', $r).'</td>';
                echo '</tr>'."\n";
            }
        }
        ?>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>