<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `InstrumentationF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Ice_Instrumentation__t_Observer;
if(!isset($Ice_Instrumentation__t_Observer))
{
    $Ice_Instrumentation__t_Observer = IcePHP_declareClass('::Ice::Instrumentation::Observer');
}

global $Ice_Instrumentation__t_CommunicatorObserver;
if(!isset($Ice_Instrumentation__t_CommunicatorObserver))
{
    $Ice_Instrumentation__t_CommunicatorObserver = IcePHP_declareClass('::Ice::Instrumentation::CommunicatorObserver');
}
?>
