<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `PermissionsVerifierF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $Glacier2__t_PermissionsVerifier;
global $Glacier2__t_PermissionsVerifierPrx;
if(!isset($Glacier2__t_PermissionsVerifier))
{
    $Glacier2__t_PermissionsVerifier = IcePHP_declareClass('::Glacier2::PermissionsVerifier');
    $Glacier2__t_PermissionsVerifierPrx = IcePHP_declareProxy('::Glacier2::PermissionsVerifier');
}

global $Glacier2__t_SSLPermissionsVerifier;
global $Glacier2__t_SSLPermissionsVerifierPrx;
if(!isset($Glacier2__t_SSLPermissionsVerifier))
{
    $Glacier2__t_SSLPermissionsVerifier = IcePHP_declareClass('::Glacier2::SSLPermissionsVerifier');
    $Glacier2__t_SSLPermissionsVerifierPrx = IcePHP_declareProxy('::Glacier2::SSLPermissionsVerifier');
}
?>
