// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `evtcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.evtcenter;

public interface triggers extends Ice.Object,
                                  _triggersOperations, _triggersOperationsNC
{
    public static final String ice_staticId = "::sooh::services::evtcenter::triggers";

    public static final long serialVersionUID = -9149318898749184241L;
}
