<div class="bjui-pageContent"><?php
    $renderer = new \Prj\Misc\FormRenderer();
    $str = $renderer->getEditStandard(\Sooh\Base\Form\Broker::getCopy('default'),1);
var_log($str, 'str>>>>>>>');
    echo $str;
?>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close" data-icon="close">取消</button></li>
        <li><button type="submit" class="btn-default" data-icon="save">保存</button></li>
    </ul>
</div>