<form action="<?php echo $exportSelUrl; ?>" method="post" id="form-exportChecked"  style="margin:0px; display: inline ">
    <span id="hid"></span>
    <div class="pull-right">
        <div class="btn-group">
            <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
            <ul class="dropdown-menu right" role="menu">
                <li><a  href="<?php echo $exportAllUrl; ?>">导出全部</a></li>
                <li><a class="excel-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>
            </ul>
        </div>
    </div>
</form>
