// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `logcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.logcenter;

/**
 * Provides type-specific helper functions.
 **/
public final class logerPrxHelper extends Ice.ObjectPrxHelperBase implements logerPrx
{
    private static final String __writeAsy_name = "writeAsy";

    public void writeAsy(String logdata, String reqdata)
    {
        writeAsy(logdata, reqdata, null, false);
    }

    public void writeAsy(String logdata, String reqdata, java.util.Map<String, String> __ctx)
    {
        writeAsy(logdata, reqdata, __ctx, true);
    }

    private void writeAsy(String logdata, String reqdata, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_writeAsy(begin_writeAsy(logdata, reqdata, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, String reqdata)
    {
        return begin_writeAsy(logdata, reqdata, null, false, false, null);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, String reqdata, java.util.Map<String, String> __ctx)
    {
        return begin_writeAsy(logdata, reqdata, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, String reqdata, Ice.Callback __cb)
    {
        return begin_writeAsy(logdata, reqdata, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, String reqdata, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_writeAsy(logdata, reqdata, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, String reqdata, Callback_loger_writeAsy __cb)
    {
        return begin_writeAsy(logdata, reqdata, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, String reqdata, java.util.Map<String, String> __ctx, Callback_loger_writeAsy __cb)
    {
        return begin_writeAsy(logdata, reqdata, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, 
                                          String reqdata, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_writeAsy(logdata, reqdata, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, 
                                          String reqdata, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_writeAsy(logdata, reqdata, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, 
                                          String reqdata, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_writeAsy(logdata, reqdata, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_writeAsy(String logdata, 
                                          String reqdata, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_writeAsy(logdata, reqdata, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_writeAsy(String logdata, 
                                           String reqdata, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_writeAsy(logdata, 
                              reqdata, 
                              __ctx, 
                              __explicitCtx, 
                              __synchronous, 
                              new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_writeAsy(String logdata, 
                                           String reqdata, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__writeAsy_name, __cb);
        try
        {
            __result.prepare(__writeAsy_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(logdata);
            __os.writeString(reqdata);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_writeAsy(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __writeAsy_name);
    }

    private static final String __writeSyn_name = "writeSyn";

    public String writeSyn(String logdata, String reqdata)
    {
        return writeSyn(logdata, reqdata, null, false);
    }

    public String writeSyn(String logdata, String reqdata, java.util.Map<String, String> __ctx)
    {
        return writeSyn(logdata, reqdata, __ctx, true);
    }

    private String writeSyn(String logdata, String reqdata, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__writeSyn_name);
        return end_writeSyn(begin_writeSyn(logdata, reqdata, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, String reqdata)
    {
        return begin_writeSyn(logdata, reqdata, null, false, false, null);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, String reqdata, java.util.Map<String, String> __ctx)
    {
        return begin_writeSyn(logdata, reqdata, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, String reqdata, Ice.Callback __cb)
    {
        return begin_writeSyn(logdata, reqdata, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, String reqdata, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_writeSyn(logdata, reqdata, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, String reqdata, Callback_loger_writeSyn __cb)
    {
        return begin_writeSyn(logdata, reqdata, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, String reqdata, java.util.Map<String, String> __ctx, Callback_loger_writeSyn __cb)
    {
        return begin_writeSyn(logdata, reqdata, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, 
                                          String reqdata, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_writeSyn(logdata, reqdata, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, 
                                          String reqdata, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_writeSyn(logdata, reqdata, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, 
                                          String reqdata, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_writeSyn(logdata, reqdata, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_writeSyn(String logdata, 
                                          String reqdata, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_writeSyn(logdata, reqdata, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_writeSyn(String logdata, 
                                           String reqdata, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_writeSyn(logdata, reqdata, __ctx, __explicitCtx, __synchronous, 
                              new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                  {
                                      public final void __completed(Ice.AsyncResult __result)
                                      {
                                          logerPrxHelper.__writeSyn_completed(this, __result);
                                      }
                                  });
    }

    private Ice.AsyncResult begin_writeSyn(String logdata, 
                                           String reqdata, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__writeSyn_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__writeSyn_name, __cb);
        try
        {
            __result.prepare(__writeSyn_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(logdata);
            __os.writeString(reqdata);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_writeSyn(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __writeSyn_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __writeSyn_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        sooh.services.logcenter.logerPrx __proxy = (sooh.services.logcenter.logerPrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_writeSyn(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static logerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), logerPrx.class, logerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static logerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), logerPrx.class, logerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static logerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), logerPrx.class, logerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static logerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), logerPrx.class, logerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static logerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, logerPrx.class, logerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static logerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, logerPrx.class, logerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::sooh::services::logcenter::loger"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, logerPrx v)
    {
        __os.writeProxy(v);
    }

    public static logerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            logerPrxHelper result = new logerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
