// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `logcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.logcenter;

public final class logerHolder extends Ice.ObjectHolderBase<loger>
{
    public
    logerHolder()
    {
    }

    public
    logerHolder(loger value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof loger)
        {
            value = (loger)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _logerDisp.ice_staticId();
    }
}
