<?php
// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Locator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once __DIR__.'/../Ice/Locator.php';

global $IceGrid__t_Registry;
global $IceGrid__t_RegistryPrx;
if(!isset($IceGrid__t_Registry))
{
    $IceGrid__t_Registry = IcePHP_declareClass('::IceGrid::Registry');
    $IceGrid__t_RegistryPrx = IcePHP_declareProxy('::IceGrid::Registry');
}

global $IceGrid__t_Query;
global $IceGrid__t_QueryPrx;
if(!isset($IceGrid__t_Query))
{
    $IceGrid__t_Query = IcePHP_declareClass('::IceGrid::Query');
    $IceGrid__t_QueryPrx = IcePHP_declareProxy('::IceGrid::Query');
}

global $IceGrid__t_Locator;
global $IceGrid__t_LocatorPrx;

if(!interface_exists('IceGrid_Locator',false))
{
    interface IceGrid_Locator extends Ice_Locator
    {
        public function getLocalRegistry();
        public function getLocalQuery();
    }

    class IceGrid_LocatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::Locator', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::Locator', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::Locator';
        }
    }

    $IceGrid__t_Locator = IcePHP_defineClass('::IceGrid::Locator', 'IceGrid_Locator', -1, true, false, $Ice__t_Object, array($Ice__t_Locator), null);

    $IceGrid__t_LocatorPrx = IcePHP_defineProxy($IceGrid__t_Locator);

    IcePHP_defineOperation($IceGrid__t_Locator, 'getLocalRegistry', 2, 2, 0, null, null, array($IceGrid__t_RegistryPrx, false, 0), null);
    IcePHP_defineOperation($IceGrid__t_Locator, 'getLocalQuery', 2, 2, 0, null, null, array($IceGrid__t_QueryPrx, false, 0), null);
}
?>
