<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1),'index'); ?>" method="post" id="wares-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader">
    <?php
	$renderer = new \Prj\Misc\FormRenderer;
	echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
    ?>
	<div class="pull-right">


		<div class="btn-group">

                    <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
                    <ul class="dropdown-menu right" role="menu">
                        <li><a  href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'index'); ?>">导出全部</a></li>
                        <li><a class="wares-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>
                        <!--
                        <li class="divider"></li>
                        <li><?php echo \Prj\Misc\View::btnDelChooseInDatagrid('xxx'); ?></li>
                        -->
                    </ul>
        </div>
        <script>
            /*
             构造表单 post 方法 提交
            */

            var ids = new Array();
            $('.wares-export').click(function(){
                if(ids.length==0)
                {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#wares-exportChecked').html('');
                for(var i in ids)
                {
                    var reg = /function[.]*/;
                    if(reg.exec(ids[i])!=null)
                    {
                        continue;
                    }
                    $('#wares-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                }
                $('#wares-exportChecked').submit();
                //window.location.href="/index.php?__=manage/managers/index&__EXCEL__=1&ids="+ids;
                return false;
            });
        </script>
	</div>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>
            <tr><?php

				$headers = $this->headers;
				foreach($headers as $k=>$v){
					echo "<th width=\"$v\" >$k</th>";//data-order-field="operation" align="center" //
				}

				?>
                <!--<th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>-->
                <th width="30"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
                <th width="300">操作</th>
            </tr>
        </thead>
        <tbody>
			<?php
            $statusColor = [
                \Prj\Consts\Wares::status_abandon=>'red',
                \Prj\Consts\Wares::status_new=>'orange',
                \Prj\Consts\Wares::status_ready=>'',
                \Prj\Consts\Wares::status_open=>'green',
                \Prj\Consts\Wares::status_go=>'',
            ];
			$records = $this->records;
			
			if(!empty($records)){
				foreach($records as $r){
                    //**过滤
                    $_pkey_val_ = \Prj\Misc\View::encodePkey($r);
                    $color = $statusColor[$r['statusCode']];
                    $r['statusCode'] = "<span style='color:".$color."'>".$r['statusCode']."</span>";
                    //**
					$_pkey_ = $r['_pkey_val_'];
					echo "<tr >";  //data-id=\"{$r['_pkey_val_']}\"
					unset($r['_pkey_val_']);
					echo '<td>'.implode('</td><td>', $r)."</td>";

					echo '<td>';
					echo '<input type="checkbox" name="ids" data-group="ids" data-toggle="icheck" value="'.$_pkey_.'">';//tgh
					echo '</td>';

					echo '<td>';
                    $notice = $this->type=='check'?"查看":"修改";
                    echo "&nbsp";
                    echo \Prj\Misc\View::btnDefaultInDatagrid('回款计划',\Sooh\Base\Tools::uri(['_waresId_eq'=>$_pkey_,'__formguid__'=>'default'],'returnPlan'));
					echo "&nbsp";
                    echo \Prj\Misc\View::btnDefaultInDatagrid('查看订单',\Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_,'__formguid__'=>'default'],'index','investment'));
					echo '</td>';
					echo "</tr>\n";
				}
			}

			?>
       </tbody>
    </table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>
