<?php $randNum = rand(1000, 9999); ?>
<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__' => 1), 'index'); ?>" method="post"
      id="wares-exportChecked-<?php echo $randNum; ?>" style="display: none;">
</form>
<div class="bjui-pageHeader">
    <?php
    $renderer = new \Prj\Misc\FormRenderer;
    echo $renderer->getSearchStandard(\Sooh\Base\Form\Broker::getCopy('default'));
    ?>

    <div class="pull-right">
<!--        <div class="btn-group">-->
<!--            <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">-->
<!--                复选框-批量操作<span class="caret"></span></button>-->
<!--            <ul class="dropdown-menu right" role="menu">-->
<!--                <li><a href="--><?php //echo \Sooh\Base\Tools::uri(array(
//                        '__EXCEL__' => 1,
//                        'where'     => $this->where
//                    ), 'index'); ?><!--">导出全部</a></li>-->
<!--                <li><a class="wares-export" href="#">导出选中</a></li>-->
<!--            </ul>-->
<!--        </div>-->
        <script>

            //构造表单 post 方法 提交

            var ids = new Array();
            $('.wares-export').click(function () {
                if (ids.length == 0) {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#wares-exportChecked-<?php echo $randNum;?>').html('');
                for (var i in ids) {
                    var reg = /function[.]*/;
                    if (reg.exec(ids[i]) != null) {
                        continue;
                    }
                    $('#wares-exportChecked-<?php echo $randNum;?>').append("<input type='hidden' name='ids[]' value='" + ids[i] + "'>");
                }
                $('#wares-exportChecked-<?php echo $randNum;?>').submit();
                //window.location.href="/index.php?__=manage/managers/index&__EXCEL__=1&ids="+ids;
                return false;
            });


        </script>
    </div>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true"
           data-toggle="tablefixed">
        <thead>
        <tr><?php
            $header = $this->header;
            foreach ($header as $k => $v) {
                echo "<th width = '" . $v . "'>";
                echo $k;
                echo "</th>";
            }

            ?>
            <th width="30"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
            <th width="300">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $rs = $this->rs;
        if (!empty($rs)) {
            foreach ($rs as $r) {
                $_pkey_val_ = $r['_pkey_val_'];
                unset($r['_pkey_val_']);
                echo "<tr>";
                foreach ($r as $k => $v) {
                    echo "<td style='height:20px !important;'>";
                    echo $v;
                    echo "</td>";
                }
                echo '<td><input type="checkbox" value="' . $_pkey_val_ . '" name="ids" data-group="ids" data-toggle="icheck"></td>';
                echo "<td>";
                echo \Prj\Misc\View::btnAjax('延期1天', \Sooh\Base\Tools::uri(['_pkey_val_' => $_pkey_val_, 'hours' => 24], 'delay'), '红包有效期将会延长1天,确定执行延期操作?');
                echo \Prj\Misc\View::btnAjax('延期2天', \Sooh\Base\Tools::uri(['_pkey_val_' => $_pkey_val_, 'hours' => 48], 'delay'), '红包有效期将会延长2天,确定执行延期操作?');
                echo \Prj\Misc\View::btnEditInDatagrid('自定义延期（小时）', \Sooh\Base\Tools::uri(['_pkey_val_' => $_pkey_val_], 'delayHours'));
                echo "</td>";
                echo "</tr>";
            }
        }
        ?>
        </tbody>
    </table>
</div>