// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `msgcenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sooh.services.msgcenter;

public interface bysmsPrx extends Ice.ObjectPrx
{
    /**
     * 发送验证码类短信，receiver是手机号
     **/
    public void sendCode(String receiver, String msg);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __ctx The Context map to send with the invocation.
     **/
    public void sendCode(String receiver, String msg, java.util.Map<String, String> __ctx);

    /**
     * 发送验证码类短信，receiver是手机号
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, String msg);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, String msg, java.util.Map<String, String> __ctx);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, String msg, Ice.Callback __cb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, String msg, Callback_bysms_sendCode __cb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, String msg, java.util.Map<String, String> __ctx, Callback_bysms_sendCode __cb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendCode(String receiver, 
                                          String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 发送验证码类短信，receiver是手机号
     * @param __result The asynchronous result object.
     **/
    public void end_sendCode(Ice.AsyncResult __result);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     **/
    public void sendNotice(String receivers, String msg);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     **/
    public void sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, String msg);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, Ice.Callback __cb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, Callback_bysms_sendNotice __cb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, String msg, java.util.Map<String, String> __ctx, Callback_bysms_sendNotice __cb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendNotice(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 发送通知类短信，receiver是逗号分隔的手机号列表
     * @param __result The asynchronous result object.
     **/
    public void end_sendNotice(Ice.AsyncResult __result);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     **/
    public void sendMarket(String receivers, String msg);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     **/
    public void sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, String msg);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, Ice.Callback __cb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, Callback_bysms_sendMarket __cb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, String msg, java.util.Map<String, String> __ctx, Callback_bysms_sendMarket __cb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_sendMarket(String receivers, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 发送营销类短信，receivers是逗号分隔的手机号列表
     * @param __result The asynchronous result object.
     **/
    public void end_sendMarket(Ice.AsyncResult __result);
}
