<?php

return <<<MSG
{
    "reg_name": {
        "event": "reg_name",
        "value": "验证码：{num_num}，欢迎您注册{brand}，请在{num_time}分钟内填写，如非本人操作，请忽略此短信。",
        "msg": "0",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "注册验证码",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;num_num为系统生成的验证码;num_time为验证码有效时长,分钟为单位"
    },
    "login_num": {
        "event": "login_num",
        "value": "您正在修改登录密码，此次验证码：{num_num}，请在{num_time}分钟内填写，如非本人操作，请忽略此短信。",
        "msg": "0",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "修改密码验证码",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;num_num为系统生成的验证码;num_time为验证码有效时长,分钟为单位 "
    },
    "suc_ok": {
        "event": "suc_ok",
        "value": "您已成功注册，{signin_redbag}元注册红包已放入您的小虾账户，快登录使用吧！完成实名认证后可以获得更多奖励哦！点击下载小虾www.xiaoxialicai.com/html/cs3/index.html",
        "msg": "0",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "注册成功",
        "exp": "tel_serve为客服电话;signin_redbag为注册时得到的红包金额"
    },
    "ask_money": {
        "event": "ask_money",
        "value": "您于{time_full}申请的{money_now}元提现已受理，预计最快次日到账。",
        "msg": "0",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "4",
        "title": "提现申请",
        "desc": "提现提醒",
        "exp": "time_full为提现操作时的时间,应精确到分钟,如:time_full=2015年12月3日12:59分;money_now为此次操作提现的金额"
    },
    "get_money": {
        "event": "get_money",
        "value": "您投资的{pro_name}理财产品本次回款{money_baby}元，如需详情请查看资金记录。",
        "msg": "1",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "3",
        "title": "回款提醒",
        "desc": "回款提醒",
        "exp": "{pro_name}为理财产品名称,如长兴一号等;{money_baby}为本次回款本金的金额。"
    },
    "recharge_ok": {
        "event": "recharge_ok",
        "value": "您已成功充值{money_recharge}元！如需详情请在平台内查看。",
        "msg": "0",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "充值成功短信提醒",
        "exp": "money_recharge为此次充值金额,元为单位,"
    },
    "suc_all": {
        "event": "suc_all",
        "value": "您已成功投资{pro_name}理财产品，请您耐心等待目标产品满额。",
        "msg": "0",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "0",
        "title": "投资成功",
        "desc": "投资成功",
        "exp": "pro_name为理财产品名称,如长兴一号等"
    },
    "look_ok": {
        "event": "look_ok",
        "value": "您投资的{pro_name}已经满标，我们将在{time_all}小时内将您投资协议的电子合同展示在您的{brand}平台{cont_ok}中，期待您的收益吧！",
        "msg": "1",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "2",
        "title": "合同下发",
        "desc": "标的已满，合同下发",
        "exp": ""
    },
    "money_start": {
        "event": "money_start",
        "value": "您投资的{pro_name}已成交，投资款{touzi_money}元开始计息，详情请查看{money_back}。",
        "msg": "1",
        "push": "1",
        "sms": "0",
        "time": "0",
        "class": "1",
        "title": "计息提醒",
        "desc": "计息提醒",
        "exp": "money_back为查看收益的栏目名称;{touzi_money}为此次投资的金额，单位为元"
    },
    "join_us": {
        "event": "join_us",
        "value": "投资成功！我们将在{time_all}小时内将您投资协议的电子合同展示在您的{brand}平台{cont_ok}中，请您之后注意查看。",
        "msg": "0",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "0",
        "title": "投资提醒",
        "desc": "合同提醒",
        "exp": "time_all为平台发送电子合同所需时间,如time_all=12或time_all=6,单位为小时;cont_ok为平台中查看合同的栏目名称,如cont_ok=投资产品详情"
    },
    "tell_data": {
        "event": "tell_data",
        "value": "您投资的{pro_name}理财产品发生提前还款，总额{money_full}元，其中提前还款本金{capital_ok}元，提前还款利息{int_ok}元。本次投资已回款完毕。",
        "msg": "1",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "3",
        "title": "提前还款",
        "desc": "提前还款说明",
        "exp": "money_full为本次还款的总金额,单位为元,小数点后最多保留两位;capital_ok为本次还款的本金的数额;int_ok为本次还款的利息数额;price_ok为本次还款的补偿金数额"
    },
    "bank_ok": {
        "event": "bank_ok",
        "value": "您于{time_baby}申请的{money_now}元提现已转入您指定的银行帐号，具体到账时间请参照各银行规定查收。",
        "msg": "1",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "4",
        "title": "提现到账",
        "desc": "提现提醒",
        "exp": "time_baby为用户申请的提现金额到达相应提现账户的时间,应精确到分钟,如:time_baby=2015年12月3日12:59分;money_now为此次操作提现的金额"
    },
    "red_loging_packet": {
        "event": "red_loging_packet",
        "value": "感谢您对{brand}的信任，送您{num_packet}个{private_gift}元注册红包,有效期为{num_deadline}小时，完成实名认证，领取更多奖励吧！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "普通注册红包",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{private_gift}为不可分享的红包金额，num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "red_log_packet": {
        "event": "red_log_packet",
        "value": "您邀请的好友已成功在{brand}投资，送您{num_packet}个{private_gift}元邀请红包，有效期为{num_deadline}小时，感谢您的信任！",
        "msg": "1",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "有邀请注册红包（老用户使用）",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{private_gift}为不可分享的红包金额，num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "red_invate_packet": {
        "event": "red_invate_packet",
        "value": "实名认证成功！您获得了{num_packet}个{private_gift}元的认证红包，有效期为{num_deadline}小时，感谢您的信任！完成首次充值，领取更多奖励！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "认证红包",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{private_gift}为不可分享的红包金额，num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "red_invite_packet": {
        "event": "red_invite_packet",
        "value": "您已成功完成首次投资，奖励{num_packet}个{private_gift}元的首购红包，有效期为{num_deadline}小时，感谢您的信任！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "首次投资",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{private_gift}为不可分享的红包金额，num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "red_recharge_packet": {
        "event": "red_recharge_packet",
        "value": "您已成功完成首次充值，奖励{num_packet}个{private_gift}元的首充红包，有效期为{num_deadline}小时，感谢您的信任！完成首次投资，领取更多奖励吧！",
        "msg": "1",
        "push": "1",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "首次充值",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{private_gift}为不可分享的红包金额，num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "red_gifted_packet": {
        "event": "red_gifted_packet",
        "value": "您已获得{num_packet}个分享红包，有效期为{num_deadline}小时，赶快把它分享给您的朋友吧！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "投资满足条件－分享红包",
        "exp": "num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "red_sign_packet": {
        "event": "red_sign_packet",
        "value": "您今日已领取{sign_money}元签到红包，明天还可以签到领奖哦！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "签到红包",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{sign_money}为本次签到平台赠送的红包金额,单位为元"
    },
    "total_got_integrate": {
        "event": "total_got_integrate",
        "value": "您已累计获得{much_jifen}积分，可以领取赏金红包哦！",
        "msg": "1",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "7",
        "title": "积分提醒",
        "desc": "赏金任务红包",
        "exp": "{much_jifen}为整数纯数字，不包含小数点，用来代表积分的数量;brand 为平台名称,如brand=小虾理财、brand=快快贷。"
    },
    "red_admire_packet": {
        "event": "red_admire_packet",
        "value": "您已成功领取{num_packet}个{private_gift}元的赏金红包，有效期为{num_deadline}小时，感谢您的信任！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "领取赏金红包后通知",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{private_gift}为不可分享的红包金额，num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "first_login_packet": {
        "event": "first_login_packet",
        "value": "您首次登录{brand}，送您{num_packet}个{private_gift}元的首次登录红包，有效期为{num_deadline}小时，感谢您的信任！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "首次登陆－见面礼红包",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{private_gift}为不可分享的红包金额，num_packet为本次收到红包的数量,要求是整数;num_deadline为红包的有限期限,为具体小时数值,要求是整数"
    },
    "return_money": {
        "event": "return_money",
        "value": "您今日共有{money_re}元返利到账，如需详情请查看资金记录。",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "6",
        "title": "返利提醒",
        "desc": "返利提醒",
        "exp": "money_re为今天返现金额的总数量,单位为元"
    },
    "ad_red": {
        "event": "ad_red",
        "value": "红包满天飞！偷偷告诉你，小虾理财又要发红包啦，快来抢！",
        "msg": "0",
        "push": "1",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "推送红包广告",
        "exp": "依广告文案而定"
    },
    "update_app": {
        "event": "update_app",
        "value": "新一年，小虾理财跟你一起进步！快来更新吧，看看我们的改变。小虾理财2.0欢喜上线！",
        "msg": "0",
        "push": "1",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "软件更新推送提醒",
        "exp": "依广告文案而定"
    },
    "birth_app": {
        "event": "birth_app",
        "value": "小虾理财一周年！小虾理财已经一周年啦，快来分享小虾的喜悦，登录平台领取生日蛋糕吧！",
        "msg": "0",
        "push": "1",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "软件活动推送广告",
        "exp": "依广告文案而定"
    },
    "remind_app": {
        "event": "remind_app",
        "value": "主人，您已经7天没有登录小虾理财啦，你不理财、财不理你呦！",
        "msg": "0",
        "push": "1",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "平台登陆提醒",
        "exp": "依广告文案而定"
    },
    "fast_name": {
        "event": "fast_name",
        "value": "您此次登录的验证码为：{num_num}，请在{num_time}分钟内填写，如非本人操作，请忽略此短信。",
        "msg": "0",
        "push": "0",
        "sms": "1",
        "time": "0",
        "class": "0",
        "title": "",
        "desc": "快捷登录验证码",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;num_num为系统生成的验证码;num_time为验证码有效时长,分钟为单位"
    },
    "code_gift": {
        "event": "code_gift",
        "value": "您此次在{brand}成功兑换了{code_gift_name}，爱理财，爱小虾！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "7",
        "title": "兑换成功",
        "desc": "兑换成功提醒",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;code_gift_name为活动兑换的奖品内容"
    },
    "saving_money": {
        "event": "saving_money",
        "value": "您此次的存钱罐收益为{saving_pot_money}元，已存入您的{brand}账户。",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "8",
        "title": "存钱罐收益",
        "desc": "存钱罐收益",
        "exp": "brand 为平台名称,如brand=小虾理财、brand=快快贷;{saving_pot_money}为此次存钱罐的收益金额，单位为元。"
    },
    "sign_in_remind": {
        "event": "sign_in_remind",
        "value": "您今天的签到红包还未领取，快来小虾理财领取现金红包吧 ！",
        "msg": "1",
        "push": "1",
        "sms": "0",
        "time": "0",
        "class": "7",
        "title": "未领取签到红包",
        "desc": "未领取签到红包提醒",
        "exp": "提醒时间为每天12：00，推送对象为未领取签到红包的完成绑卡的用户，推送周期以天为单位。"
    },
    "redpacket_kefu": {
        "event": "redpacket_kefu",
        "value": "您此次获得的{private_gift}元客服奖励红包已到账，您可以在红包列表中查看并且投资使用，祝您生活愉快！",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "5",
        "title": "红包提醒",
        "desc": "客服奖励红包",
        "exp": "{private_gift}为红包提醒"
    },
    "remind_by_push": {
        "event": "remind_by_push",
        "value": "{sell_item_name}马上就要开售啦，点我快快抢购",
        "msg": "0",
        "push": "1",
        "sms": "0",
        "time": "0",
        "class": "0",
        "title": "开标提醒",
        "desc": "开标提醒",
        "exp": "{sell_item_name}为标的名称，{remind_pushtime}为距离标的开售剩下的时间，单位为分钟"
    },
    "recharge_wrong": {
        "event": "recharge_wrong",
        "value": "您充值{money_recharge}元失败，需要重新充值。如您对资金有所疑问，请联系小虾理财客服400-101-8610。",
        "msg": "1",
        "push": "0",
        "sms": "0",
        "time": "0",
        "class": "7",
        "title": "充值失败提醒",
        "desc": "充值失败提醒",
        "exp": "money_recharge为此次充值金额,单位为元"
    }
}
MSG;
